name: Hobospider132 Stuff
author: Hobospider132
description: Just a place for me to learn webdev

baseurl: ""

exclude:
    - README.md
    - Gemfile

plugins:
    - jekyll-redirect-from

sass:
    style: compressed
