name: Osu! API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies (prod)
        run: npm install osu-api-v1-js

      - name: Set up environment variable
        run: echo "OSU_API_KEY=${{ secrets.OSU_API }}" >> $GITHUB_ENV

      - name: Run TopPlays function to update cache
        run: node JS/osu.mjs
        env:
          OSU_API_KEY: ${{ secrets.OSU_API }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Updated cache at $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
