name: Osu! API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies (prod)
        run: npm install osu-api-v1-js

      - name: Set up environment variable
        run: echo "OSU_API_KEY=${{ secrets.OSU_API }}" >> $GITHUB_ENV

      - name: Update cache
        run: node JS/osu.mjs
        env:
          OSU_API_KEY: ${{ secrets.OSU_API }}

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: JS/cache.json
          key: ${{ steps.cache-osu-restore.outputs.cache-primary-key }}
