name: Osu! API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 9 * * 0' 
    # Updates osu scores once a week 9 am utc time

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0  

      - name: Install Dependencies (prod)
        run: npm install osu-api-v1-js

      - name: Set up environment variable
        run: echo "OSU_API_KEY=${{ secrets.OSU_API }}" >> $GITHUB_ENV

      - name: Generate cache file
        run: node JS/cacheOsu.mjs
        env:
          OSU_API_KEY: ${{ secrets.OSU_API }}

      - name: Check for changes
        id: git-check
        run: echo "CHANGED=$(git status --porcelain | wc -l)" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.CHANGED != '0'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update osu! cache file [Automated] $(date +'%Y-%m-%d %H:%M:%S')"
          git push
